#!/bin/bash

# Run powersaving script
case $1 in
  battery)
    echo "Running powersaving on battery in 2 seconds"
    #sleep 2

    # screen power saving
    # Change 3 to the desired level and adjust the path to the brightness module
    echo 10 > /sys/class/backlight/acpi_video0/brightness
    #sleep 2

    # Enable DPMS and put the display to standby after 60 seconds, to suspend after 120 seconds, and turn it off after 180 seconds
    # See also http://ptspts.blogspot.nl/2009/10/screen-blanking-dpms-screen-saver.html
    #export DISPLAY=:0
    #export XAUTHORITY=/home/orschiro/.Xauthority
    #su -c "xset dpms 120 180 240" orschiro
    #sleep 2

    # Enable suspend on lid closing
    #sed -i 's/HandleLidSwitch=ignore/HandleLidSwitch=suspend/' /etc/systemd/logind.conf

    # Stop applications with systemd services
    # Stop Crashplan Engine
    systemctl stop crashplan.service
    #sleep 2
    systemctl stop dropbox@orschiro.service

    systemctl stop insync@orschiro.service
    # Kill tracker
    # if pidof tracker-miner-fs; then
    # killall tracker-miner-fs
    # fi
    # if pidof tracker-store; then
    #   killall tracker-store
    # fi

    # Stop applications with PIDs
    #for app in insync, dropbox
    #do
    #  if pidof $app; then
    #    killall $app
    #  fi
    #done
    #sleep 2

    # Disable dispatcher
    #systemctl stop NetworkManager-dispatcher 
    #sleep 2

    #systemctl disable NetworkManager-dispatcher
    #sleep 2
  ;;
  AC)
    echo "Running powersaving on AC in 2 seconds"
    #sleep 2

    # screen power saving
    echo 14 > /sys/class/backlight/acpi_video0/brightness
    #sleep 2

    #export DISPLAY=:0
    #export XAUTHORITY=/home/orschiro/.Xauthority
    #su -c "xset -dpms; xset s off" orschiro
    #sleep 2

    # Disable suspend on lid closing
    #sed -i 's/HandleLidSwitch=suspend/HandleLidSwitch=ignore/' /etc/systemd/logind.conf

    # Restart dispatcher
    #systemctl restart NetworkManager
    #systemctl enable NetworkManager-dispatcher
    #sleep 2

    #systemctl restart NetworkManager-dispatcher
    #sleep 2

    # Start Crashplan Engine
    systemctl restart crashplan.service
    #sleep 2

    systemctl restart insync@orschiro.service
    systemctl restart dropbox@orschiro.service
    # Restart Dropbox
    #systemctl enable dropbox@orschiro
    #systemctl restart dropbox@orschiro
    #su -c "dropboxd &" orschiro
    #sleep 2

    # Start Insync
    #su -c "insync start &" orschiro

    #for app in "insync start", dropboxd
    #do
    #  su -c "$app" orschiro
    #done

  ;;
  *)
    echo "Determining if on AC or battery"
    if cat /sys/class/power_supply/AC/online | grep 0 > /dev/null 2>&1
    then
      echo "Laptop is on battery"
      /usr/bin/powersaving battery
    else
      echo "Laptop is on AC"
      /usr/bin/powersaving AC
    fi
  ;;
esac
