#!/bin/bash

# Run powersaving script
case $1 in
  battery)
    echo "Running powersaving on battery in 2 seconds"
    #sleep 2

    # screen power saving
    # Change 3 to the desired level and adjust the path to the brightness module
    echo 10 > /sys/class/backlight/acpi_video0/brightness
    #sleep 2

    # Enable DPMS and put the display to standby after 60 seconds, to suspend after 120 seconds, and turn it off after 180 seconds
    # See also http://ptspts.blogspot.nl/2009/10/screen-blanking-dpms-screen-saver.html
    #export DISPLAY=:0
    #export XAUTHORITY=/home/orschiro/.Xauthority
    su -c "xset dpms 120 180 240" orschiro
    
    # Compositor
    killall compton
    
    # Pulseaudio
    killall pulseaudio
    
    # Webcam autosuspend
    echo 'auto' > '/sys/bus/usb/devices/7-6/power/control';

    # Enable suspend on lid closing
    #sed -i 's/HandleLidSwitch=ignore/HandleLidSwitch=suspend/' /etc/systemd/logind.conf

    # Stopping applications
    systemctl stop crashplan.service
    systemctl stop dropbox@orschiro.service
    systemctl stop insync@orschiro.service
    
  ;;
  AC)
    echo "Running powersaving on AC in 2 seconds"
    #sleep 2

    # screen power saving
    echo 14 > /sys/class/backlight/acpi_video0/brightness
    #sleep 2

    #export DISPLAY=:0
    #export XAUTHORITY=/home/orschiro/.Xauthority
    su -c "xset -dpms; xset s off" orschiro
    #sleep 2

    # Compositor
    ps cax | grep compton > /dev/null
    if [ $? -eq 0 ]; then
      echo "Compton is running."
    else
      echo "Compton is not running."
      su -c "compton -bcC -o 0.3 &" orschiro
    fi
    
    # Pulse
    ps cax | grep pulseaudio > /dev/null
    if [ $? -eq 0 ]; then
      echo "Pulseaudio is running."
    else
      echo "Pulseaudio is not running."
      su -c "pulseaudio --start &" orschiro
    fi
    
    # Disable suspend on lid closing
    #sed -i 's/HandleLidSwitch=suspend/HandleLidSwitch=ignore/' /etc/systemd/logind.conf

    # Restarting applications
    systemctl restart crashplan.service
    systemctl restart insync@orschiro.service
    systemctl restart dropbox@orschiro.service

  ;;
  *)
    echo "Determining if on AC or battery"
    if cat /sys/class/power_supply/AC/online | grep 0 > /dev/null 2>&1
    then
      echo "Laptop is on battery"
      /usr/bin/powersaving battery
    else
      echo "Laptop is on AC"
      /usr/bin/powersaving AC
    fi
  ;;
esac
